APEXMALHAR-2242 Added user documentation for 0.9 version of Kafka Input Operator
apache/apex-malhar pull request #420
Opened 2016-09-21 06:49 UTC by chaithu14

2016-09-21 16:28 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
>  ### AbstractKafkaInputOperator
Since both have the same name, add the the package name in brackets for both so users can distinguish them.

2016-09-21 16:32 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +for consuming messages from Kafka messaging system. This operator has key features like fault-tolerant, scalable, multi-cluster support, multi-topic support.
Rewrite both sentences something like this:
This version uses the new 0.9 version of the Consumer API; differences between the two API versions are described here <provide a suitable link>.
This operator is fault-tolerant, scalable, and has multi-cluster and multi-topic support.

2016-09-21 16:33 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +0.9.0. So, this operator will work with any 0.9.x version of Apache Kafka.
Rewrite:
This operator requires version 0.9.0 or later of the Kafka Consumer API.

2016-09-27 16:38 UTC, chaithu14 commented
Incorporated the review comments and updated the PR.

2016-09-30 20:40 UTC, tweise commented on docs/operators/kafkaInputOperator.md
>  ### AbstractKafkaInputOperator
It's not the 0.8 version of the operator but the operator for Kafka 0.8.x

2016-09-30 20:47 UTC, tweise requested changes

2016-09-30 20:47 UTC, tweise commented on docs/operators/kafkaInputOperator.md
> +This operator requires version 0.9.0 or later of the Kafka Consumer API.
I think this document should explain what the ready to use operators are. AbstractXXX is for implementing custom operator.

2016-09-30 20:47 UTC, tweise commented on docs/operators/kafkaInputOperator.md
> +Below is the code snippet:
Instead of putting all the code here, the example will probably be more useful for developers.

2016-10-03 06:48 UTC, chaithu14 commented on docs/operators/kafkaInputOperator.md
>  ### AbstractKafkaInputOperator
Done.

2016-10-03 06:55 UTC, chaithu14 commented on docs/operators/kafkaInputOperator.md
> +This operator requires version 0.9.0 or later of the Kafka Consumer API.
Concrete operators are also covered in next section.

2016-10-03 06:56 UTC, chaithu14 commented on docs/operators/kafkaInputOperator.md
> +Below is the code snippet:
Link to example is provided at the end of doc.

2016-10-11 22:47 UTC, tweise commented
I think that currently the documentation repeats a lot of javadoc, instead it should explain how common tasks are solved. See 

https://issues.apache.org/jira/browse/APEXMALHAR-2287
https://issues.apache.org/jira/browse/APEXMALHAR-2288

Note what 2287 is asking for, it's based on the questions on the users list and not really covered here.

@amberarrow thoughts?

2016-10-12 16:30 UTC, amberarrow commented
Yes, some narrative style text that discusses how to use this operator in a couple of common use cases would be helpful. Some of the descriptions of the configurable parameters have useful data.

My initial thought is a "How to use" section that starts by discussing the 0.8 and 0.9 APIs, then input versus output, then the notion of topics and partitions and how they map to operator partitions, then performance related issues, exactly once, and closing with troubleshooting common problems. Not cast in stone but something along those lines.

2016-10-12 17:17 UTC, chaithu14 commented
Thanks @tweise and @amberarrow for reviewing.
Please consider this as initial version of doc and merge this PR. @tweise created JIRA's for each of the versions. I will work on those new JIRA's.

2016-10-13 02:57 UTC, tweise commented
There are a few basic changes that haven't been made. But instead of more ping pong I will submit these for inclusion into the PR and then it will need to be rebased.

2016-10-13 04:00 UTC, tweise commented
@chaithu14 sent you PR for the changes. LMK when this PR is rebased.

2016-10-13 08:07 UTC, chaithu14 commented
@tweise Re-based the changes and updated the PR.

2016-10-13 13:59 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +        APPLICATION_OR_EARLIEST => Operator consume messages from committed position from last run. If there is no committed offset, then it starts consuming from beginning of kafka queue.
consume => consumes

2016-10-13 14:00 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +        APPLICATION_OR_LATEST => Operator consume messages from committed position from last run. If there is not committed offset, then it starts consuming from latest position of queue.
consume => consumes

2016-10-13 14:06 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +    -   Specifies that the operator will process the same set of messages in a window before and after a failure. This is important but it comes with higher cost because at the end of each window the
Specifies ... => If set to a value other than the default, such as `FSWindowDataManager`, specifies ....

2016-10-13 14:07 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +void emitTuple(String cluster, ConsumerRecord<byte[], byte[]> message): Abstract method that emits tuples
Please surround code fragments with backquotes.

2016-10-13 14:08 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +This class extends from AbstractKafkaInputOperator and define the getTuple() method which extracts byte array from Kafka message.
getTuple() needs backquotes around it.

2016-10-13 14:08 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +outputPort <byte[]>: Tuples extracted from Kafka messages are emitted through this port.
backquotes needed

2016-10-13 14:10 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +https://mvnrepository.com/artifact/org.apache.apex/malhar-kafka
This link (and others below) should be formatted as markdown links.

2016-10-13 14:32 UTC, tweise commented
@chaithu14 there was no need to squash the extra commit since it wasn't yours. Can you give me write access to your fork so I can make the remaining edits, update the PR and merge it.

2016-10-13 16:31 UTC, tweise commented
@amberarrow addressed comments, please merge.

2016-10-13 17:10 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +For a full example application project, refer to https://github.com/DataTorrent/examples/tree/master/tutorials/kafka.
This link doesn't show as a clickable link in the rendered page.

2016-10-13 17:12 UTC, amberarrow commented on docs/operators/kafkaInputOperator.md
> +-   ***clusters*** - String[]
This should be formatted as an HTML table to be consistent with the others above.

2016-10-13 17:13 UTC, amberarrow commented
Made a couple of additional comments; I'll merge after those are addressed.

2016-10-13 17:28 UTC, tweise commented on docs/operators/kafkaInputOperator.md
> +-   ***clusters*** - String[]
This wasn't brought up earlier and can be addressed separately. Should also consider which format is more suitable.

2016-10-13 17:28 UTC, tweise commented
Fixed link, please merge.

2016-10-13 17:41 UTC, merged