APEXMALHAR-2335 APEXMALHAR-2333 APEXMALHAR-2334 #resolve #comment Pro…
apache/apex-malhar pull request #493
Opened 2016-11-10 23:00 UTC by brightchen

…blems on StateTracker

2016-11-10 23:00 UTC, brightchen commented
@davidyan74 Please review

2016-11-11 16:45 UTC, brightchen commented
@davidyan74 please review

2016-11-11 20:48 UTC, davidyan74 requested changes

2016-11-11 20:48 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/Bucket.java
> +      while ((clearWindowId = committedData.floorKey(windowId)) != null) {
each floorKey and remove call is O(log n) so the loop is going to be O(n log n). Why don't we just have a normal ordered iteration to make it O(n) instead?

2016-11-11 20:48 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +
Can we make some of these members final?

2016-11-11 20:48 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +        if (o1.bucketId == o2.bucketId) {
why do we need this if statement?

2016-11-11 21:16 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +  private transient ReadWriteLock bucketAcessLock = new ReentrantReadWriteLock();
spelling

2016-11-11 21:20 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +        } finally {
Not sure what this code is doing. Is it the same as putting all items in bucketHeapForAccess to bucketHeapForRelease?

2016-11-12 00:57 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +    accessedBucketIds.add(bucketId);
accessBucketIds is not a ConcurrentSet. Won't this create a problem when multiple threads call this method?

2016-11-12 01:19 UTC, brightchen commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +    accessedBucketIds.add(bucketId);
accessedBucketIds all used by operator main thread

2016-11-12 02:09 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +
I think these two TreeSets and the BucketIdTimeWrapper can be replaced by a LinkedHashMap with accessOrder = true

2016-11-12 02:19 UTC, brightchen commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +
it is possible to it by a map from time to a list of bucket. but seems not simplify the code. The reason to use two lists in order two threads can run without concurrent control. the concurrent control only need to happen when merge/swap

2016-11-12 02:26 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +
Please take a look at this and let me know what you think:
https://github.com/apache/apex-malhar/commit/eadf39b11f495e84c1d1e6ffbb83c20b8dee404b

2016-11-13 16:54 UTC, brightchen commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +
it is possible that last update time is different. for example: in first 500ms, updated b1, b2; in second 500ms, updated b2, b3, so the last update of b1 is different from last update of b2 and b3

2016-11-14 23:45 UTC, davidyan74 commented on library/src/main/java/org/apache/apex/malhar/lib/state/managed/StateTracker.java
> +
This is my latest FYI: https://github.com/davidyan74/apex-malhar/tree/bucketLastAccess

2016-11-15 00:31 UTC, brightchen commented
@davidyan74 Merged your update, please review

2016-11-15 02:10 UTC, merged